apiVersion: apps/v1
kind: Deployment
metadata:
  name: psdn-ui-deployment
  labels:
    app: psdn-ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: psdn-ui-deployment
  template:
    metadata:
      labels:
        app: psdn-ui-deployment
    spec:
      containers:
        - name: psdn-ui-deployment
          image: eunsangacr.azurecr.io/psdn-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 443
            - containerPort: 80
          volumeMounts:
            - name: tls-certificates
              mountPath: "/etc/nginx/ssl"
              readOnly: true
      volumes:
        - name: tls-certificates
          secret:
            secretName: my-tls-secret
