apiVersion: v1
kind: Service
metadata:
  name: psdn-ui-front-service
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: psdn-ui-development
