name: Image Build for a SPA Container and Push to ACR
on:
  workflow_dispatch:

jobs:
  prepare-and-push-docker-environment:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: eunsangacr
      ACR_URL: eunsangacr.azurecr.io
      ACR_IMAGE_NAME: psdn-ui
      AKS_CLUSTSER_NAME: psdn
      AZURE_RESOURCE_GROUP: MetLife-Project-Research

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Log in to Azure CLI with Service Principal
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }} \
            --allow-no-subscriptions

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build Docker image
        run: |
          docker build \
          --build-arg REACT_APP_AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }} \
          -t ${{ env.ACR_URL }}/${{ env.ACR_IMAGE_NAME }} \
          -f ./Dockerfile .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.ACR_URL }}/${{ env.ACR_IMAGE_NAME }}:latest  

      - name: Set Kubernetes Context
        uses: azure/aks-set-context@v4
        with:
           resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
           cluster-name: ${{ env.AKS_CLUSTSER_NAME }}

      - name: Apply Kubernetes manifest
        run: |
          kubectl apply -f ./k8s/deployment.yml
          kubectl apply -f ./k8s/service.yml

      - name: Log out from Azure CLI
        run: az logout
